### ISSUE TITLE
Responsive issue on mobile 

### ISSUE THREAD

**Issue by theetrain** [TechnologyMasters/technologymasters.github.io#1]
The home page's hero/fold area has a couple responsive issues
1. Logo is too high 
2. Downward arrow covers "join now" and "sign in" buttons. 

I'm interested in contributing. What jekyll dependencies do I need for development?

**Comment by ahmadnassri** [comment]
PRs welcome :)

the site is a gh-pages site, details here: https://help.github.com/articles/setting-up-your-pages-site-locally-with-jekyll/

**Comment by theetrain** [comment]
PR submitted.

**Comment by ahmadnassri** [comment]
@theetrain thanks for this, it just so happens that @amanullahtanweer also did the same fix for mobile AT THE SAME TIME!

can you please review your PR and see if additional changes are warranted for merging?

thanks.

**Comment by theetrain** [comment]
I have added some more commits to the PR, now ready to merge.

I had mainly worked on the hero area and @amanullahtanweer's changes are now consolidated with mine.

**Comment by theetrain** [comment]
Need to fix Fireside Conf image.

**Comment by ahmadnassri** [comment]
make a new issue for that ^
