### ISSUE TITLE
Purge/Rename channels

### ISSUE THREAD

**Issue by theetrain** [TechnologyMasters/technologymasters.github.io#26]
Rename:
- [x] #producthuntto -> #producthunt

Remove from default channels:
- [x] #firesideconf

Purge:
?

**Comment by theetrain** [comment]
How about we send out a purge notice for the following channels, giving people 1 week to move to their umbrella channel?
- ~~#ux -> #design~~ (canned)
- ~~#security, #science -> #technology~~ (canned)
- [ ] #apis -> #programming
- [x] #oakville -> #toronto
- ~~#making -> #homeautomation (rename to #diy)~~ (canned)

**Comment by ahmadnassri** [comment]
#security #science and #technology should remain apart

#making & #automation, not sold on that change.
