### ISSUE TITLE
Getting Started in a Tech Career

### ISSUE THREAD

**Issue by theetrain** [TechnologyMasters/technologymasters.github.io#32]
After some fun discussion this past week, newbies want to know how TM members got started on their careers, and how to get started on theirs. Answers are going to vary wildly, so let's make this as easy-to-follow as we can:
- types of IT careers that exist (not all IT is programming)
- types of Programming careers that are hot, fun, pay well, etc
- What sort of education is most effective for programming/IT? Network security and engineering jobs, for instance, favour education over development jobs.
- How important is it to find a job that matches your interests and expertise?
- Thoughts on mentorships, bootcamps, and online courses
- Reference 'How We Learn'
- Individual stories
- Thoughts on working at startups, enterprise, classic business, freelancing, and entrepreneurship
- How you, a beginner, can get started in a programming career.

Start here: http://techmasters.slackarchive.io/general/-/1479509109.011798/1479761311.01194/1479761058011912/

**Comment by kellkevin** [comment]
I'll take this on if it ever comes up.
