### ISSUE TITLE
Full-Time Employment vs Contract

### ISSUE THREAD

**Issue by theetrain** [TechnologyMasters/technologymasters.github.io#33]
- What are key differences?
- Pros and Cons
- Short-term and long-term benefits for each
- Subjective Preferences

**Comment by Katorthoma** [comment]
Was assigned to Kevin Kelly.
Draft link here: https://medium.com/@kellkevin/full-time-employment-vs-contracting-freelancing-76e1ecc0d260

**Comment by theetrain** [comment]
Published: https://blog.techmasters.chat/full-time-employment-vs-contracting-freelancing-76e1ecc0d260#.dw08q9p4x
