### ISSUE TITLE
Developer Job Roles: present, upcoming, and soon to be gone

### ISSUE THREAD

**Issue by theetrain** [TechnologyMasters/technologymasters.github.io#45]
- What job roles are in high-demand?
- Does every job role perfectly define their responsibilities?
- What are some emergent job roles you've noticed in recent years?
- Which job roles do you think won't last, or may soon see very low demand?
- What are examples of 'developer support' roles you can name?

Start here http://techmasters.slackarchive.io/general/-/1478387694.009654/1478550452.009784/1478549915009771/

**Comment by bradstimpson** [comment]
I'll cover this one
